"""
CTI Report DOCX Styles — fonts, colors, heading styles, header/footer.
"""
from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm, Emu
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.section import WD_ORIENT
from docx.oxml.ns import qn, nsdecls
from docx.oxml import parse_xml
import datetime

# --- CTI House Palette ---------------------------------------------------------
# The palette lives in cti_palette.py (hex, dependency-free) so the matplotlib figures can read it
# without python-docx; the RGBColor table below is DERIVED from it. Change a colour there and every
# DOCX chart, table, heading and house-report figure follows.
from cti_palette import (FONT_BODY, FONT_HEADING, FONT_MONO,  # noqa: E402,F401
                         COLORS_HEX, CYCLE_HEX, SEVERITY_COLORS_HEX, hex_rgb)

COLORS = {k: RGBColor(*hex_rgb(v)) for k, v in COLORS_HEX.items()}

SEVERITY_COLORS = {k: RGBColor(*hex_rgb(v)) for k, v in SEVERITY_COLORS_HEX.items()}

# Cell-shading strings (raw hex, no '#') DERIVED from the palette above — so the
# one place to change the header band / zebra colour is COLORS_HEX, not scattered
# literals in postprocess/sections. set_cell_shading() wants the bare hex.
SHADE_BAND = COLORS_HEX["band"].lstrip("#")       # table header band
SHADE_ZEBRA = COLORS_HEX["bg_light"].lstrip("#")  # zebra stripe


def setup_styles(doc: Document) -> Document:
    """Configure document styles for CTI report."""
    style = doc.styles["Normal"]
    style.font.name = FONT_BODY
    style.font.size = Pt(10.5)
    style.font.color.rgb = COLORS["text"]
    style.paragraph_format.space_after = Pt(6)
    style.paragraph_format.line_spacing = 1.15

    for level, size, color in [
        ("Heading 1", 18, "primary"),   # slate
        ("Heading 2", 14, "steel"),
        ("Heading 3", 12, "steel"),
    ]:
        s = doc.styles[level]
        s.font.name = FONT_HEADING
        s.font.size = Pt(size)
        s.font.bold = True
        s.font.color.rgb = COLORS[color]
        s.paragraph_format.space_before = Pt(18 if level == "Heading 1" else 12)
        s.paragraph_format.space_after = Pt(8)

    return doc


def add_page_number(paragraph):
    """Add page number field to a paragraph."""
    run = paragraph.add_run()
    fldChar1 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="begin"/>')
    run._r.append(fldChar1)

    run2 = paragraph.add_run()
    instrText = parse_xml(f'<w:instrText {nsdecls("w")} xml:space="preserve"> PAGE </w:instrText>')
    run2._r.append(instrText)

    run3 = paragraph.add_run()
    fldChar2 = parse_xml(f'<w:fldChar {nsdecls("w")} w:fldCharType="end"/>')
    run3._r.append(fldChar2)


def setup_header_footer(doc: Document, report_id: str, classification: str = "OPEN SOURCE"):
    """Add header with classification and footer with page numbers."""
    section = doc.sections[0]
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.5)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.5)

    # Header
    header = section.header
    header.is_linked_to_previous = False
    hp = header.paragraphs[0]
    hp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = hp.add_run(f"CTI REPORT  |  {classification}  |  {report_id}")
    run.font.size = Pt(8)
    run.font.color.rgb = COLORS["muted"]
    run.font.name = FONT_HEADING

    # Footer
    footer = section.footer
    footer.is_linked_to_previous = False
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = fp.add_run(f"CTI Report — {report_id}  |  Page ")
    run.font.size = Pt(8)
    run.font.color.rgb = COLORS["muted"]
    run.font.name = FONT_HEADING
    add_page_number(fp)

    # Credit line — CTI Expert attribution on every generated report.
    cp = footer.add_paragraph()
    cp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    crun = cp.add_run("Generated by CTI Expert  ·  https://github.com/7onez/cti-expert")
    crun.font.size = Pt(7)
    crun.font.color.rgb = COLORS["muted"]
    crun.font.name = FONT_HEADING

    return doc


def add_cover_page(doc: Document, data: dict) -> Document:
    """Create professional cover page with CTI Report title."""
    # Spacer
    for _ in range(4):
        doc.add_paragraph()

    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run("CTI REPORT")
    run.font.size = Pt(34)
    run.font.bold = True
    run.font.color.rgb = COLORS["primary"]
    run.font.name = FONT_HEADING

    # Subtitle — case label
    sub_para = doc.add_paragraph()
    sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sub_para.add_run(data.get("case", {}).get("label", "Intelligence Summary"))
    run.font.size = Pt(18)
    run.font.color.rgb = COLORS["accent"]
    run.font.name = FONT_HEADING

    # Divider line
    div_para = doc.add_paragraph()
    div_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = div_para.add_run("_" * 50)
    run.font.color.rgb = COLORS["border"]

    doc.add_paragraph()

    # Metadata table
    case = data.get("case", {})
    meta_items = [
        ("Report ID", case.get("id", "N/A")),
        ("Classification", case.get("classification", "OPEN SOURCE")),
        ("Date", case.get("date", datetime.date.today().isoformat())),
        ("Analyst", case.get("analyst", "AI-Assisted OSINT")),
        ("Subject", case.get("subject", "N/A")),
        ("Status", case.get("status", "active")),
    ]

    table = doc.add_table(rows=len(meta_items), cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, (label, value) in enumerate(meta_items):
        row = table.rows[i]
        cell_l = row.cells[0]
        cell_r = row.cells[1]
        cell_l.width = Inches(2)
        cell_r.width = Inches(4)

        run_l = cell_l.paragraphs[0].add_run(label)
        run_l.font.bold = True
        run_l.font.size = Pt(11)
        run_l.font.color.rgb = COLORS["muted"]
        cell_l.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT

        run_r = cell_r.paragraphs[0].add_run(value)
        run_r.font.size = Pt(11)
        run_r.font.color.rgb = COLORS["text"]

    # Remove table borders for clean look
    for row in table.rows:
        for cell in row.cells:
            tc = cell._tc
            tcPr = tc.get_or_add_tcPr()
            tcBorders = parse_xml(
                f'<w:tcBorders {nsdecls("w")}>'
                '<w:top w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
                '<w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
                '<w:bottom w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
                '<w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/>'
                "</w:tcBorders>"
            )
            tcPr.append(tcBorders)

    # Page break after cover
    doc.add_page_break()

    return doc



def enable_update_fields(doc: Document) -> Document:
    """Flag document fields (esp. the TOC) to refresh when the file is opened.

    Word honors this and regenerates a page-numbered TOC automatically on open.
    Headless LibreOffice (the PDF path) does NOT update fields, so the real,
    clickable TOC is baked into the field's cache separately (see cti_docx_toc).
    Idempotent."""
    settings = doc.settings.element
    existing = settings.find(qn("w:updateFields"))
    if existing is None:
        settings.append(parse_xml(f'<w:updateFields {nsdecls("w")} w:val="true"/>'))
    else:
        existing.set(qn("w:val"), "true")
    return doc


def set_cell_shading(cell, color_hex: str):
    """Set background color of a table cell."""
    shading = parse_xml(
        f'<w:shd {nsdecls("w")} w:fill="{color_hex}" w:val="clear"/>'
    )
    cell._tc.get_or_add_tcPr().append(shading)
